### ISSUE TITLE
SSR: Cannot read property 'clear' of undefined

### ISSUE THREAD

**Issue by Linzdigr** [vuematerial/vue-material#1272]
On the last version, v1.0.0-beta-7, I've got an error on the server runtime render :

```
TypeError: Cannot read property 'clear' of undefined
    at VueComponent.clear ([...]/foo/node_modules/vue-material/dist/vue-material.js:1384:26)
    at VueComponent.<anonymous> ([...]/foo/node_modules/vue/dist/vue.runtime.common.js:457:26)
    at Watcher.get ([...]/foo/node_modules/vue/dist/vue.runtime.common.js:3092:25)
    at new Watcher ([...]/foo/node_modules/vue/dist/vue.runtime.common.js:3081:12)
    at VueComponent.Vue.$watch ([...]/foo/node_modules/vue/dist/vue.runtime.common.js:3554:19)
    at createWatcher ([...]/foo/node_modules/vue/dist/vue.runtime.common.js:3514:13)
    at initWatch ([...]/foo/node_modules/vue/dist/vue.runtime.common.js:3496:7)
    at initState ([...]/foo/node_modules/vue/dist/vue.runtime.common.js:3267:5)
    at VueComponent.Vue._init ([...]/foo/node_modules/vue/dist/vue.runtime.common.js:4519:5)
    at new VueComponent ([...]/foo/node_modules/vue/dist/vue.runtime.common.js:4691:12)
```

Is there something specific to do for SSR?

**Comment by Samuell1** [comment]
Version of Vue and do you using some code or only importing vue-material?

**Comment by Linzdigr** [comment]
Vue 2.5.9
Actually it's hard to say, it's a migration project from 0.8.1 to the beta but the error seems to occur pretty early in the process.

**Comment by Linzdigr** [comment]
Any advice to put me on track?

**Comment by Samuell1** [comment]
Looks like problem is here: https://github.com/vuematerial/vue-material/blob/dev/dist/vue-material.js#L1384

**Comment by Linzdigr** [comment]
Like a clearable md-input? Actually yes, tried to remove all use of md-clearable and still the same.

**Comment by Samuell1** [comment]
@Linzdigr error is same or its changed?

**Comment by Linzdigr** [comment]
Error hasn't changed, no autocomplete in the project. Still looking for the element causing this.

**Comment by Samuell1** [comment]
I tested `md-clearable` on md-field with NuxtJs and without error.

**Comment by BernardMarieOnzo** [comment]
hi I'm using the version 1.0.0-beta-7, I don't got errors but vue-material tags are not recognize,
I have create:
plugins/vue-material
`import Vue from 'vue'

if (process.BROWSER_BUILD) {
  const VueMaterial = require('vue-material')
  Vue.use(VueMaterial)
}
`
and in nuxt.config.js I did 
`build: {vendor: [ 'vue-material' ]}`
and 
`plugins: [ '~/plugins/vue-material.js']`

**Comment by Samuell1** [comment]
@BernardMarieOnzo Hey, If you using nuxtjs we have for it boilerplate for fast and simple starts without any setups needed. https://github.com/vuematerial/nuxtjs
