### ISSUE TITLE
npm installation fails on WSL

### ISSUE THREAD

**Issue by RichardJECooke** [vuematerial/vue-material#1440]
My Vue web app builds and runs fine on Ubuntu 17.10 on bare metal.

But when trying to npm update on Ubuntu 16.04 on the Windows subsystem for Linux everything builds and runs fine except for vue-material.

I get this error log for  "vue-material": "^1.0.0-beta-7",

```
8523 verbose lifecycle vue-material@1.0.0~postinstall: CWD: /mnt/c/data/dailypractice/src_simple/node_modules/vue-material
8524 silly lifecycle vue-material@1.0.0~postinstall: Args: [ '-c', 'sh build/git-hooks/install.sh' ]
8525 info lifecycle vue-material@1.0.0~postinstall: Failed to exec postinstall script
8526 verbose unlock done using /home/rje/.npm/_locks/staging-ccdf710d63a54b7c.lock for /mnt/c/data/dailypractice/src_simple/node_modules/.staging
8527 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
8528 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
8529 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
8529 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
8529 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
8529 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
8530 verbose stack Error: vue-material@1.0.0 postinstall: `sh build/git-hooks/install.sh`
8530 verbose stack spawn ENOENT
8530 verbose stack     at ChildProcess.<anonymous> (/home/rje/.nvm/versions/node/v9.3.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
8530 verbose stack     at ChildProcess.emit (events.js:159:13)
8530 verbose stack     at maybeClose (internal/child_process.js:943:16)
8530 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
8531 verbose pkgid vue-material@1.0.0
8532 verbose cwd /mnt/c/data/dailypractice/src_simple
8533 verbose Linux 4.4.0-43-Microsoft
8534 verbose argv "/home/rje/.nvm/versions/node/v9.3.0/bin/node" "/home/rje/.nvm/versions/node/v9.3.0/bin/npm" "update"
8535 verbose node v9.3.0
8536 verbose npm  v5.5.1
8537 error file sh
8538 error code ELIFECYCLE
8539 error errno ENOENT
8540 error syscall spawn
8541 error vue-material@1.0.0 postinstall: `sh build/git-hooks/install.sh`
8541 error spawn ENOENT
8542 error Failed at the vue-material@1.0.0 postinstall script.
8542 error This is probably not a problem with npm. There is likely additional logging output above.
8543 verbose exit [ 1, true ]
```

Any ideas what the error is and what to try please?  I've already checked that I've got build-essentials installed.

**Comment by Samuell1** [comment]
Change your version in package to: `vuematerial@beta`

**Comment by RichardJECooke** [comment]
Neither of these are accepted as valid tags by npm, please would you clarify:

"vue-material": "@beta",
"vue-material": "vuematerial@beta",

**Comment by Samuell1** [comment]
`"vue-material": "beta"`

**Comment by RichardJECooke** [comment]
Now I'm getting

```Error: EACCES: permission denied, rename '/mnt/c/data/dailypractice/src_simple/node_modules/mixin-deep' -> '/mnt/c/data/dailypractice/src_simple/node_modules/.mixin-deep.DELETE'```

I tried changing owner as shown here https://unix.stackexchange.com/questions/222231/how-to-properly-recursively-chown-files-including-hidden-dirs

```sudo chown rje:rje *``` and ```.``` and other variations

but the node_modules owner isn't changing, it remains on root.

I also tried deleting the node_modules folder and restarting bash on Windows

**Comment by RichardJECooke** [comment]
Ok, deleting the entire project and recloning from git works fine. Closing. Thanks a lot @Samuell1
